"""empty message

Revision ID: 1c5636cf7e1b
Revises: 6532d7a902e9
Create Date: 2019-08-24 17:41:46.441515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c5636cf7e1b'
down_revision = '6532d7a902e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Project', sa.Column('description', sa.Text(), nullable=True))
    op.drop_column('Project', 'device_uuid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Project', sa.Column('device_uuid', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    op.drop_column('Project', 'description')
    # ### end Alembic commands ###
